version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/data:/var/lib/postgresql/data
      - ./assets/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
